run:
  deadline: 5m
  allow-parallel-runners: true
  skip-files:
  - /zz_generated_
  - _generated_
  - _test
  skip-dirs:
  - generated
  tests: true
  build-tags:
  - test
linters-settings:
  goimports:
    local-prefixes: github.com/oneblock-ai/oneblock
linters:
  disable-all: true
  enable:
  - goimports
  - gofmt
  - misspell
  - revive
  - gosec
  - prealloc
