apiVersion: ml.oneblock.ai/v1
kind: MLService
metadata:
  name: mistral-7b-llm
  namespace: default
spec:
  modelTemplateVersionRef:
    name: mistral-7b-instruct-v02
    namespace: default
  mlClusterRef:
    rayClusterSpec:
      image: "anyscale/ray-llm:0.5.0"
      workerGroupSpec:
      - name: small-wg
        replicas: 1
        minReplicas: 1
        maxReplicas: 5
        acceleratorTypes:
          Nvidia-A10G: 1
        rayStartParams:
          block: 'true'
        resources:
          limits:
            cpu: 8
            memory: 12Gi
          requests:
            cpu: 4
            memory: 8Gi
        volume:
          name: mistral-7b-llm-small-wg-log
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
