apiVersion: ml.oneblock.ai/v1
kind: ModelTemplate
metadata:
  name: mistral-7b-instruct-v02
spec:
  description: "This is a model template for the Yi-6B model from 01.AI."
---
apiVersion: ml.oneblock.ai/v1
kind: ModelTemplateVersion
metadata:
  name: mistral-7b-instruct-v02
spec:
  templateName: mistral-7b-instruct-v02
  # modelID is the ID that refers to the model in the OpenAI API.
  modelID: "mistralai/Mistral-7B-Instruct-v0.2"
  hfModelID: "mistralai/Mistral-7B-Instruct-v0.2"
  engineConfig:
    type: VLLMEngine
    maxTotalTokens: 4096
    # LLM engine keyword arguments passed when constructing the model.
    vLLMArgs: |
      trust_remote_code: true
      max_num_batched_tokens: 4096
      max_num_seq: 32
  deploymentConfig:
    replicas: 1
    maxReplicas: 5
    maxConcurrentQueries: 64
  scalingConfig:
    # The GPUs per worker is default to 1, if you want to using multiple GPUs just set numWorkers to be the number of GPUs you want to use.
    numWorkers: 1
    numCPUsPerWorker: 8
