apiVersion: ml.oneblock.ai/v1
kind: Notebook
metadata:
  name: nb-jupyter
  namespace: default
  labels:
    ml.oneblock.ai/notebook-type: jupyter
  annotations:
    oneblock.ai/volumeClaimTemplates: '[{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"name":"nb-jupyter"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}]'
spec:
  serviceType: NodePort
  template:
    spec:
      containers:
      - image: kubeflownotebookswg/jupyter-scipy:v1.8.0
        name: nb-jupyter
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
#          limits:
#            nvidia.com/gpu: 1 # optional, requesting 1 GPU
        volumeMounts:
        - mountPath: /home/jovyan
          name: test-vol
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: nb-jupyter # keep the name to be consistent with the annotation volumeClaimTemplates
      - emptyDir:
          medium: Memory
        name: dshm
